name: stock_game_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.1
  flutter_displaymode: ^0.6.0
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  measure_size: ^4.0.0
  rxdart: ^0.27.7
  bottom_sheet: ^4.0.4
  lottie_tgs: ^2.7.1
  socket_io_client: ^2.0.3+1
  chat_bubbles: ^1.6.0
  infinite_scroll_pagination: ^4.0.0
  flutter_in_app_pip: ^1.7.3
  flutter_bootstrap: ^2.0.0
  flutter_inappwebview: ^6.0.0
  permission_handler: ^11.3.1
  carousel_slider: ^4.2.1
  flutter_animate: ^4.5.0
  video_player: ^2.9.1
  flutter_custom_carousel: ^0.1.0+1
  flutter_staggered_grid_view: ^0.7.0
  visibility_detector: ^0.4.0+2
  animations: ^2.0.11
  auto_orientation: ^2.3.1
  # chatview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependency_overrides:
  webview_flutter_android: 3.16.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
